import { Provider } from "@/components/Provider";
import { repositoryName } from "@/lib/prismicio";
import "@/styles/globals.css";
import { PrismicPreview } from "@prismicio/next";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  variable: "--font-roboto",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ignews",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <Provider>
        <body className={`${roboto.variable}`}>{children}</body>
        <PrismicPreview repositoryName={repositoryName} />
      </Provider>
    </html>
  );
}
